Add tests
alex-solovyev/task-manager-python pull request #7
Opened 2023-08-29 15:23 UTC by alex-solovyev

2023-08-29 20:39 UTC, aleksandr-semenov-dbp requested changes

2023-08-29 20:39 UTC, aleksandr-semenov-dbp commented on test/test_admin.py
> +        tomorrow = datetime.now() + timedelta(1)
если нужна дата, то дату и нужно делать date.today()

2023-08-30 05:18 UTC, alex-solovyev commented on test/test_admin.py
> +        tomorrow = datetime.now() + timedelta(1)
thanks, done

2023-08-30 09:28 UTC, aleksandr-semenov-dbp approved these changes

2023-08-30 09:42 UTC, merged